services:
  train:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: train-app
    networks:
      - shared-net
    volumes:
      - ../scripts:/training-app/scripts
      - ../configs:/training-app/configs
    ports:
      - "8081:8081"
    env_file:
      - ../.env
    restart: "no"
    environment:
      - ENV=production
      - JUPYTER_TOKEN=1234

networks:
  shared-net:
    name: ml-network
    external: true # joins the already-created network
