services:
  train:
     build:
       context: ..
       network: host
       dockerfile: infra/Dockerfile 
     container_name: train-app
     volumes:
       - ../scripts:/training-app/scripts
       - ../configs:/training-app/configs
     ports: 
       - "8081:8081"
     env_file:
        - ../.env
     restart: "no"
     environment:
        - ENV=production
        - JUPYTER_TOKEN=1234